[2023-07-23T15:07:04.018+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: BigC_assignment.step_1_insert_data manual__2023-07-23T15:06:51.606383+00:00 [queued]>
[2023-07-23T15:07:04.051+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: BigC_assignment.step_1_insert_data manual__2023-07-23T15:06:51.606383+00:00 [queued]>
[2023-07-23T15:07:04.052+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-07-23T15:07:04.054+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 4
[2023-07-23T15:07:04.060+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-07-23T15:07:04.112+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): step_1_insert_data> on 2023-07-23 15:06:51.606383+00:00
[2023-07-23T15:07:04.128+0000] {standard_task_runner.py:54} INFO - Started process 1840 to run task
[2023-07-23T15:07:04.146+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'BigC_assignment', 'step_1_insert_data', 'manual__2023-07-23T15:06:51.606383+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/bigc_assignment_pipeline.py', '--cfg-path', '/tmp/tmpt9hm2vbj']
[2023-07-23T15:07:04.161+0000] {standard_task_runner.py:83} INFO - Job 6: Subtask step_1_insert_data
[2023-07-23T15:07:04.164+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/bigc_assignment_pipeline.py
[2023-07-23T15:07:05.712+0000] {task_command.py:384} INFO - Running <TaskInstance: BigC_assignment.step_1_insert_data manual__2023-07-23T15:06:51.606383+00:00 [running]> on host 8d374bbcaaec
[2023-07-23T15:07:05.873+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Pitchakorn_Prasertmet
AIRFLOW_CTX_DAG_ID=BigC_assignment
AIRFLOW_CTX_TASK_ID=step_1_insert_data
AIRFLOW_CTX_EXECUTION_DATE=2023-07-23T15:06:51.606383+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-07-23T15:06:51.606383+00:00
[2023-07-23T15:07:05.951+0000] {logging_mixin.py:117} INFO - (1221, 14)
[2023-07-23T15:07:05.959+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/step_1_insert_data.py", line 51, in insert_data
    cur.execute(insert_query)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "product_pkey"
DETAIL:  Key (sku)=(Os206_3141_S) already exists.

[2023-07-23T15:07:05.987+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=BigC_assignment, task_id=step_1_insert_data, execution_date=20230723T150651, start_date=20230723T150704, end_date=20230723T150705
[2023-07-23T15:07:06.019+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 6 for task step_1_insert_data (duplicate key value violates unique constraint "product_pkey"
DETAIL:  Key (sku)=(Os206_3141_S) already exists.
; 1840)
[2023-07-23T15:07:06.093+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-07-23T15:07:06.206+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
